# OBJECTIVE 2 EXPLORE THE ORDERS TABLE ;

#Q1.  VIEW THE ORDER DETAILS TABLE 
SELECT*FROM ORDER_DETAILS;

#Q2.	WHAT IS THE DATE RANGE OF THE TABLE?

SELECT *FROM ORDER_DETAILS
ORDER BY ORDER_DATE;

SELECT MIN(ORDER_DATE),MAX(ORDER_DATE) FROM ORDER_DETAILS;

# "This will give me the minimum and maximum date range of the data. You can use MIN and MAX instead of using ORDER BY."


#Q3.	HOW MANY ORDERS WERE MADE WITHIN THIS DATE RANGE
SELECT*FROM ORDER_DETAILS;

SELECT COUNT( DISTINCT ORDER_ID) AS NO_OF_ORDERS
FROM ORDER_DETAILS;
"As ORDER ID is repeating, I can't just count the number of rows in the table. 
I have to find the number of unique orders that were made. To do this, I have to use the DISTINCT keyword.";

# Q4.	HOW MANY ITEMS WERE ORDERED WITHIN THIS DATE RANGE
SELECT*FROM ORDER_DETAILS;
SELECT COUNT(ITEM_ID) AS ITEM_COUNT
FROM ORDER_DETAILS;


# Q5.	WHICH ORDER HAD THE MOST NUMBER OF ITEMS?
SELECT*FROM ORDER_DETAILS;

SELECT ORDER_ID,COUNT(ITEM_ID) AS NO_OF_ITEMS
FROM ORDER_DETAILS
GROUP BY ORDER_ID
ORDER BY NO_OF_ITEMS DESC ;

" I WANT TO KNOW THE NUMBER OF ORDERS WITH THE MOST ITEMS  SO TO DO THIS  M GOING TO SORT THE NUM ITEMS COLUM N BY    ORDER BY NO_OF_ITEMS DESC
THIS WILL SHOW U FOR THESE NO OF ORDERS THESE NO OF ITEMS WERE ORDERED
THIS WILL SHOW U BY EACH ORDER ID HOW MANY ITEMS WERE ADDED"

# Q6.	HOW MANY ORDERS HAD MORE THAN 12 ITEMS?
THIS WILL SHOW ME ALL THE ORDERS WHO HAVE ORDERED MORE THAM 12 ITEMS
SELECT ORDER_ID,COUNT(ITEM_ID) AS NO_OF_ITEMS
FROM ORDER_DETAILS
GROUP BY ORDER_ID
HAVING NO_OF_ITEMS>12


NOW WE HAVE ASKED TO SHOW HOW MANY ORDERS I.E COUNT SO WE HAVE USED SUBQUERRY HERE TO CALCULATE IT;

SELECT COUNT(*) FROM
(SELECT ORDER_ID,COUNT(ITEM_ID) AS NO_OF_ITEMS
FROM ORDER_DETAILS
GROUP BY ORDER_ID
HAVING NO_OF_ITEMS>12) AS NO_OF_ORDERS;

"# WITH THIS OBJECTIVE OUR GOAL WAS TO EXPLORE THE ORDER _DETAILS TABLE 	
AND NOW I  M HABVING A PRETTY GOOD IDEA ABOUT THE WHATS IN THE ORDER DETILS TABLE"



















