

# 1.combine the menu_items and order_details tables into a single table?;
SELECT *FROM MENU_ITEMS;
SELECT*FROM ORDER_DETAILS;
SELECT * FROM 
ORDER_DETAILS AS OD LEFT JOIN MENU_ITEMS AS MI ON MI.MENU_ITEM_ID=OD.ITEM_ID;

# 2. WHAT WERE THE LEAST AND MOST ORDERED ITEMS ? WHAT CATEGORIES WERE THEY IN?


(SELECT ITEM_NAME,CATEGORY,COUNT(ORDER_DETAILS_ID) AS NO_OF_ORDERS
FROM ORDER_DETAILS AS OD JOIN MENU_ITEMS AS MI ON OD.ITEM_ID=MI.MENU_ITEM_ID
GROUP BY ITEM_NAME,CATEGORY
ORDER BY NO_OF_ORDERS
LIMIT 1)

UNION ALL

(SELECT ITEM_NAME,CATEGORY,COUNT(ORDER_DETAILS_ID) AS NO_OF_ORDERS
FROM ORDER_DETAILS AS OD JOIN MENU_ITEMS AS MI ON OD.ITEM_ID=MI.MENU_ITEM_ID
GROUP BY ITEM_NAME,CATEGORY
ORDER BY NO_OF_ORDERS DESC
LIMIT 1);






# 3. WHAT WERE THE TOP 5 ORDERS THAT SPENT THE MOST MONEY?

SELECT ORDER_ID,SUM(PRICE) AS TOTAL_SPEND
FROM ORDER_DETAILS AS OD LEFT JOIN MENU_ITEMS AS MI ON OD.ITEM_ID=MI.MENU_ITEM_ID
GROUP BY ORDER_ID
ORDER BY TOTAL_SPEND DESC
LIMIT 5;





# 4. VIEW THE DETAILS OF HIGHEST SPENT ORDER?WHAT INSIGHTS CAN U GATHER FROM RESULTS?

SELECT CATEGORY,ORDER_ID,SUM(PRICE) AS HIGHEST_SPEND
FROM ORDER_DETAILS AS OD LEFT JOIN MENU_ITEMS AS MI ON OD.ITEM_ID=MI.MENU_ITEM_ID
GROUP BY CATEGORY,ORDER_ID
ORDER BY HIGHEST_SPEND DESC
LIMIT 1;

" THE INSIGHT WE GATHERED HERE IS THAT WE SHOULD KEEP THOSE EXPENSIVE ITALIAN DISHES ON OUR MENU BQZ PEOPLE
SEEM TO BE ORDERING THEM A LOT ESPECIALLY OUR HIGHEST SPEND CUSTOMERS"



SELECT ORDER_ID,CATEGORY,COUNT(ITEM_ID) AS NO_OF_ITEMS,SUM(PRICE)AS HIGHEST_SPEND
 FROM ORDER_DETAILS AS OD LEFT JOIN MENU_ITEMS AS MI ON
OD.ITEM_ID=MI.MENU_ITEM_ID
WHERE ORDER_ID=440
GROUP BY ORDER_ID,CATEGORY;


# 5. VIEW THE DETAILS OF TOP 5 HIGHEST SPENT ORDER?WHAT INSIGHTS CAN U GATHER FROM RESULTS?

SELECT ORDER_ID,CATEGORY,COUNT(ITEM_ID) AS NUMBER_OF_ITEMS,SUM(PRICE)AS HIGHEST_SPEND
FROM ORDER_DETAILS AS OD LEFT JOIN MENU_ITEMS AS MI ON OD.ITEM_ID=MI.MENU_ITEM_ID
WHERE ORDER_ID IN (440,2075,1957,330,2675)
GROUP BY ORDER_ID,CATEGORY;
" THE INSIGHT WE GATHERED HERE IS THAT WE SHOULD KEEP THOSE EXPENSIVE ITALIAN DISHES ON OUR MENU BQZ PEOPLE
SEEM TO BE ORDERING THEM A LOT ESPECIALLY OUR HIGHEST SPEND CUSTOMERS"

