create database restaurant_db;


select*from menu_items;
select*from order_details;

# Q1. View the menu_items;

Select*from menu_items;

# Q2. FINF THE NUMBER OF ITEMS IN THE MENU 

SELECT COUNT(*)  AS COUNT_OF_ITEMS FROM MENU_ITEMS;
SELECT COUNT(MENU_ITEM_ID) FROM MENU_ITEMS;

# Q3  WHAT ARE THE LEAST AND MOST EXPENSIVE ITEMS  ON THE MENU? 

Select*from menu_items
Order by price; 


SELECT*FROM MENU_ITEMS
ORDER BY PRICE;

SELECT PRICE,
CASE WHEN PRICE>13 THEN "MOST_EXPENSIVE"
	WHEN PRICE>10 THEN "MOST_EXPENSIVE"
	   ELSE "LEAST EXPENSIVE"
    END AS CUSTOMER_CATEGORY
FROM MENU_ITEMS
GROUP BY PRICE
ORDER BY CUSTOMER_CATEGORY DESC;
    